const STRING = {
    Warrning:{
        Data: 'Silakan setujui syarat dan ketentuan dan lengkapi data anda.',
        NoData: 'Data tidak di temukan silakan coba lagi',
        ACTION: 'reject',
        confirmPassword : 'Password tidal sesuai',
        field_name_error :'Nama harus diisi',
        field_alfa_name_error :'Nama Pemesan harus alfabet',
        field_email_error:'Email harus diisi',
        field_number_error:'No. Handphone harus diisi',
        field_fullname_error:'Nama lengkap wajib diisi',
        field_idcard_error:'Silakan isi nomor identitas.',
        field_wrong_email:'Format Email salah',
        field_wrong_character:'Hanya boleh disi dengan huruf',
        field_wrong_number:'Hanya boleh disi dengan angka',
        seat : 'Klik terlebih dahulu kursi yang anda pilih sebelumnya untuk menonaktifkan.',
        seat_not_availabel : 'Mohon maaf kursi sudah terisi.',
        no_connection :'Silakan periksa koneksi internet Anda'
    },
    Label : {
        detil : 'Detail',
        closeButton : 'Ganti Tanggal',
        one_way : 'One way',
        round_trip : 'Round trip',
        token : 'Token Listrik',
        tag : 'Tagihan Listrik',        
        org : 'Kota Asal',
        dep : 'Kota Tujuan',
        org_date : 'Tanggal Berangkat',
        dep_date : 'Tanggal Kembali',
        adult : 'Dewasa',
        child : 'Anak (2-11 thn)',
        infant : 'Bayi (-2 thn)',
        client : 'Silakan lengkapi data pemesan',
        Guest : 'Silakan lengkapi data tamu',
        client_name : 'Nama Pemesan',
        client_name_holder : 'Sesuai KTP/Paspor/SIM',
        client_email : 'Email Pemesan',
        client_email_holder : 'Contoh : email@example.com',
        client_phonde : 'No. Handphonde',
        client_phonde_holder : 'Contoh: 08787xxxxx',
        adult_passenger : 'Penumpang Dewasa',
        child_passenger : 'Penumpang Anak',
        infant_passenger : 'Penumpang Bayi',
        title : 'Title',
        full_name : 'Nama Lengkap',
        card_number : 'No. Identitas',
        phone : 'No. Handphone',
        brith_date : 'Tanggal Lahir',
        terms_and_conditions : 'Syarat dan Ketentuan',
        more : 'Selanjutnya',
        check_box : 'Saya memastikan semua data valid dan Saya menyetujui syarat dan ketentuan yang berlaku.',
        check_box_guest : 'Sama dengan pemesan.',
        price_poeple : 'Harga',
        ppn_title : 'Termasuk semua pajak dan biaya penerbangan',
        please_wait : 'Mohon tunggu',
        page : 'Sedang memuat halaman',
        detil_payment : 'Detail Pemesanan',
        waitting_for_Booking : 'Kami sedang memproses pemesanan Anda. Ini dapat berlangsung selama beberapa menit',
        waitting_for_Login : 'Harap tunggu',
        checkIn_date :'Tanggal Check In',
        checkOut_date :'Tanggal Check Out',
        duration : 'Durasi',
        guest :'Tamu',
        numberOf_room :'Jumlah Kamar',
        recent_Search :'Recent Booking',
        check_out :'Check-out',
        payment_method :'Pilih Metode Pembayaran',
        email_address :'Alamat Email',
        password :'Password',
        signIn : 'Login',
        forget_password :'Lupa Pasword?',
        ask_account :'Belum memiliki Akun?',
        signUp: 'Daftar',
        welcome_login :'Silakan masuk untuk bertransaksi di Padiciti',
        welcome_register:'Bergabung bersama Padiciti',
        assign :'Lengkapi data dibawah ini',
        account_name :'Nama Lengkap',
        account_hp: 'Nomor Handphone',
        repeatPassword :'Ulangi Password',
        please_fill_in : 'Bagian ini harus di isi',
        help_center : 'Pusat Bantuan',
        country : 'Negara',
        country_pass: 'Kewarganegaraan',
        issuingCountry : 'Negara Pengesah Passport',
        passport : 'Nomor Passport',
        expiryPassport : 'Tanggal Kadaluarsa',
        currency : 'Mata Uang',
        button_save :'SIMPAN',
        booking_list :'Daftar Pembelian',
        desc_booking_list:'pembelian belum selesai',
        bookingNonActive :'Belum Ada Pesanan Aktif',
        itemBooking:'Seluruh pesanan Anda akan muncul disini, tapi kini Anda belum punya satu pun. Mari buat pesanan via homepage!',
        org_date_bus:'Tanggal Keberangkatan',
        dep_date_bus:'Tanggal Pulang',
        org_bus:'Bus Pergi',
        dep_bus:'Bus Pulang',
        fit_idcard :'Sesuai KTP/Passpor/SIM',
        email_subscribers:'Email Pemesan',
        ex_email:'Contoh: email@example.com',
        no_telp:'No. Telephone',
        ex_telp:'Contoh: 081234567890',
        station_name :'Nama Stasiun atau Kota',
        flight_detail :'Detail Penerbangan',
        city_name: 'Nama Kota atau Provinsi',
        range_price:'Kisaran harga per malam',
        star_label :'Bintang',
        hotel_name:'Destinasi/Nama Hotel',
        facility:'Fasilitas',
        near_favorite_place :'Tempat Menarik Terdekat',
        others :'Lainnya',
        costumer_data :'Data Penumpang',
        profile :'Profil',
        credit_card :'Kartu Kredit',
        costumer_profile :'Profil Penumpang',
        notif :'Notifikasi',
        review :'Ulasan',
        call_me : 'Hubungi Kami',
        org_train :'Kereta Pergi',
        dep_train :'Kereta Pulang',
        train_detail :'Detail Kereta',
        station :'Stasiun',
        directly :'Langsung',
        notfound_data :'Data tidak ditemukan',
        anotherDate :'LIHAT TANGGAL LAIN'
    },
    Passanger : {
        title : 'Passenger', 
        payment_title : 'Detail Pembayaran',
        payment_go : 'Rincian Harga Pergi',
        payment_back : 'Rincian Harga Pulang',
        guest:'Guest',
        adult : 'Dewasa',
        child : 'Anak',
        infant : 'Bayi',
        tax : 'Pajak',
        Insurance : 'Asuransi',
        extraFee : 'Biaya Tambahan',
        adminFee : 'Biaya Admin',
        discount : 'Diskon',
        servicesFee : 'Biaya Jasa',
        price_go : 'Rincian Harga Penerbangan Pergi',
        price_goback : 'Rincian Harga Penerbangan Pulang'
    },
    payment : {
        chouse : 'Pilih Metode Pembayaran', 
        total : 'Total'
    },
    Label_Flight:{
        lbl_flight : 'Pesawat',
        lbl_org_flight: 'Penerbangan Pergi',
        lbl_dep_flight: 'Penerbangan Pulang',
        search : 'Cari Tiket Pesawat',
        seach_hotel :'Cari Kamar Hotel',
        transit : 'Transit di ',
        for :'untuk ',
        baggage : 'Bagasi 20 kg',
        food : 'Makanan',
        passenger : 'Passenger Service Charge',
        Airport : 'Bandara'

    },
    Function_name:{
        sort :'URUTKAN',
        filter:'FILTER',
        date_change :'GANTI TANGGAL',
        time:'Waktu',
        class:'Kelas',
        train_name :'Nama Kereta',
        airline:'Maskapai',
        numberOf_transits :'Jumlah Transit',
        choose_custumerdata:'Silakan pilih data penumpang',
    },
    Transport:{
        etiket_flight:'E-tiket Penerbangan',
        etiket_hotel :'E-tiket Hotel',
        etiket_train :'E-tiket Kereta',
        etiket_bus :'E-tiket Bus',
        flight :'Pesawat',
        hotel :'Hotel',
        train :'Kereta',
        bus :'Bus',

    },  Label_Pelni:{
        btn_search :'Cari Tiket Pelni',
        title_booking:'Kapal Keberangkatan',
        class :'Golongan',
        pelni_detail :'Detail Kapal'
    }

}

const STRING_TR = {
    LABEL: {
        ONEWAY: 'One way',
        RETURN: 'Round trip',
        ORG: 'Kota Asal',
        DEST: 'Kota Tujuan',
        ORG_PH: 'Pilih Stasiun/Kota',
        DEST_PH: 'Pilih Stasiun/Kota',
        ORG_SEAPORTS: 'Pelabuhan Asal',
        DEST_SEAPORTS: 'Pelabuhan Tujuan',
        ORG_PH_SEAPORTS: 'Pilih Pelabuhan/Kota',
        DEST_PH_SEAPORTS: 'Pilih Pelabuhan/Kota',
        DEPART_DATE: 'Tanggal Berangkat',
        RETURN_DATE: 'Tanggal Pulang',
        PASSENGER: {
            ADULT: 'Dewasa',
            INFANT: 'Bayi',
            INFANT_MAX_AGE: '(-2 thn)'
        },
        success : 'Berhasil mengubah kursi',
        failed : 'Mohon maaf gagal merubah kursi',
        BTN_SEARCH: 'Cari Tiket Kereta',
    },
    CHECKOUT: {
        TOOLBAR_TITLE: 'Penumpang dan Pemesan11',
        ALERT: {
            TITLE: 'Silakan lengkapi data pemesan',
            LIST : [
                ['Semua data E-Ticketing akan dikirim melalui Email pemesan.'],
                ['Nomor Handphone digunakan untuk informasi semua yang berkaitan dengan reservasi dan keberangkatan.']
            ]
        },
        S_N_K : {
            TITLE: 'Syarat dan Ketentuan',
            LIST : [
                ['Nama Penumpang rute internasional harus tepat dan sesuai Paspor, sedangkan domestik dapat sesuai KTP/SIM/Paspor. Karena setelah ini data penumpang tidak bisa diubah kembali.'],
                ['Nomor identitas dapat menggunakan KTP/SIM/Paspor/Kartu Pelajar.'],
                ['Nomor handphone yang diisikan harus benar untuk keperluan informasi keberangkatan.'],
                ['Jika tidak memiliki nomor handphone, penumpang dapat menggunakan nomor handphone keluarga atau kerabat dekat.'],
                ['KAMI TIDAK BERTANGGUNG JAWAB ATAS KESALAHAN PENGISIAN DATA PADA SAAT PENUKARAN TIKET ASLI.']
            ]
        },
        AGREEMENT: 'Saya memastikan semua data valid dan Saya menyetujui syarat dan ketentuan yang berlaku.'
    },
}


export {STRING, STRING_TR}